version: "3.4"

services:
  api:
    image: ghcr.io/saleor/saleor:3.15.4
    restart: unless-stopped
    network_mode: "host"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
      - jaeger
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media
    env_file:
      - common.env
      - backend.env
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - DASHBOARD_URL=http://localhost:9000/
      - ALLOWED_HOSTS=localhost,api

  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:3.15.2
    ports:
      - 9000:80
    restart: unless-stopped

  db:
    image: library/postgres:13-alpine
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - saleor-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  redis:
    image: library/redis:7.0-alpine
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - saleor-redis:/data

  worker:
    image: ghcr.io/saleor/saleor:3.15.4
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - common.env
      - backend.env
    depends_on:
      - redis
      - mailpit
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media

  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    network_mode: "host"

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    network_mode: "host"

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge
